films_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filmsapp.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filmsapp/urls.py
from django.urls import path
from . import views
app_name='filmsapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),

]

filmsapp/models.py
from django.db import models

# Create your models here.
class Movies(models.Model):
    name=models.CharField(max_length=200)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.name

filmsapp/forms.py
from django import forms
from . models import Movies
class MovieForm(forms.ModelForm):
    class Meta:
        model=Movies
        fields=[
            'name','desc','year','img'
        ]

filmsapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from filmsapp.models import Movies
from . forms import MovieForm

# Create your views here.
def index(request):
    movie=Movies.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)

def detail(request,movie_id):
    movie=Movies.objects.get(id=movie_id)

    return render(request,'detail.html',{'movie':movie})
def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img=request.FILES['img']
        movie=Movies(name=name,desc=desc,year=year,img=img)
        movie.save()
        return redirect('/')
    return render(request,'add.html')
def update(request,id):
    movie=Movies.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})
def delete(request,id):
    if request.method=='POST':
        movie = Movies.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
          <div class="col-md-4">
          </div>
         <div class="col-md-8">
             <h2 style="color:red;">ADD A NEW MOVIE</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input class="mt-3" type="text" name="name" placeholder="Enter your movie name"><br>
    <input class="mt-3" type="text" name="desc" placeholder="Enter movie description"><br>
    <input class="mt-3" type="text" name="year" placeholder="Enter year of movie release"><br>
    <input class="mt-3" type="file" name="img"><br>
    <input class="mt-3" type="submit">
</form>
         </div>
 <div class="col-md-4">
          </div>
    </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'filmsapp:index' %}">
    Online Movie Store
  </a>
    <a class="navbar-brand" href="{% url 'filmsapp:add_movie' %}">
   Add
  </a>
</nav>
{% block body %}

{% endblock %}
</body>
</html>

templates/delete.html
<div class="container">
    <div class="row">
        <div class="col-md-4">
          </div>
        <div class="col-md-8">
            <form method="POST">
    {% csrf_token %}
    <h4 style="color:blue;">Are you wanted to delete this movie</h4>
    <input type="submit" value="Yes">
</form>
        </div>
    </div>
</div>

templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container ">
    <div class="row">
        <div class="col-md-6">
           <img src="{{movie.img.url}}" width="300" height="300">
        </div>
        <div class="col-md-6">
            <h4 style="color:#212F3C;">Movie Id:{{movie.id}}</h4>
            <h3 style="color:#212F3C;">{{movie.name}}</h3>
            <h4 style="color:#212F3C;">{{movie.desc}}</h4>
            <h4 style="color:#212F3C;">Year:{{movie.year}}</h4>
            <a class="btn btn-warning" href="{% url 'filmsapp:update' movie.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'filmsapp:delete' movie.id %}">Delete</a>
        </div>
    </div>
</div>



</body>
</html>
{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
          </div>
         <div class="col-md-8">
             <h2 style="color:red;">UPDATE HERE....................</h2>
        <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
             </div>
    </div>
</div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="column">
    <div class="row">

        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card mt-3" style="width: 18rem margin-right:10rem;">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap"  height="300">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>

                    <a href="{% url 'filmsapp:detail' i.id %}" class="btn btn-primary">More Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
        </div>
</div>



{% endblock %}